# Generated by Django 3.0.3 on 2020-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='thumbnail.png', upload_to='Images'),
        ),
    ]
