# Generated by Django 3.0.3 on 2020-04-05 19:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+254700123432', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
